### ISSUE TITLE
Equation number overlaps equation

### ISSUE THREAD

**Issue by Kaba2** [mathjax/MathJax#1189]
I am having problems with the automatic equation numbering (autoNumber: "all") overlapping a long equation:

![number_overlap](https://cloud.githubusercontent.com/assets/2399754/7556298/dcd65b22-f773-11e4-92a5-4a2debbf4784.png)

The html for this is given by

```html
<div class="Example">
<p>A function <span class="latex-math"><script type="math/tex">f : \mathbb{R}^n \to \mathbb{R}^m</script></span> is <em>continuous</em> at <span class="latex-math"><script type="math/tex">p</script></span>, if</p>
<p><span class="display-latex-math"><script type="math/tex; mode=display">\forall \varepsilon \in \mathbb{R}^{> 0}: \exists \delta \in \mathbb{R}^{> 0}: \forall x \in \mathbb{R}^{d} : \left\lVert x - p \right\rVert < \delta \implies \left\lVert f(x) - f(p) \right\rVert < \varepsilon.</script></span></p>
</div>
```

and the CSS is given by

```css
.Example
{
    padding: 0.75em;
    margin-top: 1em;
    margin-bottom: 1em;
    border: 0.25em solid #8A8;
    overflow: auto;
}
```

Any ideas?

**Comment by pkra** [comment]
We'd need a live sample to rule out a bug.  But the screenshot indicates that the container is simply not wide enough to fit both the equation and it's label. So something has to give. (Automatic) line-breaking would help. There are currently no options for controlling this situation more generally.

Related are #957, #1190, #596 and others. Marking this duplicate for now.

**Comment by Kaba2** [comment]
Here is a minimal sample. These files should be stored in the same directory.

test.html
---

```html
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title></title>
<link rel="stylesheet" type="text/css" href="test.css"/>
<script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?delayStartupUntilConfig"></script>
<script type="text/javascript" src="mathjax-config.js"></script>
</head>
<body>
<div id = "remark-all">
<div id = "remark">
<div class="Example">
<p><span class="display-latex-math"><script type="math/tex; mode=display">\forall \varepsilon \in \mathbb{R}^{> 0}: \exists \delta \in \mathbb{R}^{> 0}: \forall x \in \mathbb{R}^n : \left\lVert x - p \right\rVert < \delta \implies \left\lVert f(x) - f(p) \right\rVert < \varepsilon.</script></span></p>
</div>
</div>
</div>
</body>
</html>
```

test.css
---

```css
html, body 
{
    margin: 0em;
    padding: 0em;
}

#remark-all
{
    font-family: Sans-serif;
    max-width: 40em;
    margin: auto;
    padding: 0.5em;
}

#remark
{
    line-height: 1.3em;
    min-height: 100vh;
}

#remark .Example
{
    padding: 0.75em;
    margin-top: 1em;
    margin-bottom: 1em;
    border: 0.25em solid #8A8;
    overflow: auto;
}
```

mathjax_config.js
---

```javascript
MathJax.Hub.Config({
    config: 
    [
        "MMLorHTML.js"
    ],
    jax: 
    [
        "input/TeX",
        //"input/MathML",
        "input/AsciiMath",
        "output/HTML-CSS",
        "output/NativeMML", 
        "output/CommonHTML"
    ],
    extensions: 
    [
        "tex2jax.js",
        //"mml2jax.js",
        "asciimath2jax.js",
        "MathMenu.js",
        "MathZoom.js", 
        "CHTML-preview.js"
    ],
    TeX: 
    {
        extensions: 
        [
            "AMSmath.js",
            "AMSsymbols.js",
            "noErrors.js",
            "noUndefined.js"
        ],
        equationNumbers: 
        { 
            autoNumber: "all" 
        }    
    },
    asciimath2jax: 
    {
        delimiters: [],
        ignoreClass: 'remark-all',
        processClass: 'ascii-math'
    },
    tex2jax: 
    {
        inlineMath: [],
        displayMath: [],
        ignoreClass: 'remark-all',
        processClass: 'latex-math|display-latex-math'
    }
});

MathJax.Hub.Configured();
```
