### ISSUE TITLE
cannot style font with HTML-CSS

### ISSUE THREAD

**Issue by benjaminp** [mathjax/MathJax#122]
I can put

``` CSS
math, .MathJax {
    color: orange;
}
```

in my stylesheet and all math will be colored orange. However, this does not work:

``` CSS
math, .MathJax {
    font-style: italic;
}
```

for HTML-CSS; the font-style will still be normal.
