### ISSUE TITLE
Common-HTML doesn't take well to being listed

### ISSUE THREAD

**Issue by connerbw** [mathjax/MathJax#2164]
Common-HTML doesn't take well to being listed. It creates unecessary space between listed elements. Here are some screenshots to illustrate what I mean:

**Common-HTML:**

![listing-problems-1](https://user-images.githubusercontent.com/812192/60685095-45bbba00-9e6f-11e9-8336-6b17999f6d8e.png)

Compare this to the same output, but using **HTML-CSS:**

![listing-problems-2](https://user-images.githubusercontent.com/812192/60685100-47857d80-9e6f-11e9-9293-c819b7abb3bf.png)

I am not suggesting changing this CSS is the fix since "I have no idea what I'm doing" but in Chrome Inspector if I change:

```css
.mjx-full-width {
    text-align: center;
    display: table-cell!important;
    width: 10000em;
}
```

to

```css
.mjx-full-width {
    text-align: center;
}
```

Common-HTML behaves like HTML-CSS, which is what I expect to happen. Any ideas?

Here's the test page: 

+ https://dactest1.textopress.com/chapter/mathjax-common-html-problems/

(Note to future selves, test page is temporary, will disappear once problem is resolved)
