### ISSUE TITLE
Scrolling with equation refs does not always work with SVG output

### ISSUE THREAD

**Issue by pdmosses** [mathjax/MathJax#2586]
### Issue Summary

Clicking on links produced by `\eqref` sometimes doesn't scroll to the target location when using SVG output with MathJax v3.1.2 in Safari. Clicking on the same links scrolls correctly in Firefox.

Issue #297 reported a similar problem with `\eqref` and SVG in v2.1.

Strangely, the Safari behaviour appears to depend on the form of the label: `x:z` scrolls correctly, whereas `xyz` doesn't!

### Steps to Reproduce:

1. Visit https://pdmosses.github.io/eqref.html in Safari
2. Scroll down to the bottom of the page (so the top of the page is hidden) and click on the link to `(2)`. The window **does not scroll up** to show the target equation.
3. Scroll down to the bottom of the page, and click on the link to `(1)`. The window **does scroll up** to show the target equation.
4. In Firefox, both steps 2 and 3 scroll up to the target equation.

Clicking on a valid link to an equation should always scroll to reveal the targeted equation text. 

(In fact the link to `(1)` scrolls up only to the baseline of the equation, so the equation text isn't actually visible; but that is a relatively minor, separate issue.)

### Technical details:

* MathJax Version: 3.1.2
* Client OS: Mac OS X 10.15.7
* Browser: Safari 14.0.2 (the problem doesn't seem to arise in Firefox 83.0)

### Supporting information:

 * Please supply a link to a (live) minimal example page, when possible.

    https://pdmosses.github.io/eqref.html

 * Check your browser console window for any error messages, and include them here.

    None.

 * Include the MathJax configuration you are using, and the script tag that loads MathJax itself.

```yaml
mathjax:
  source: 
     "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js"
  config:
    "{ 
      tex: { 
        tags: 'ams',
        packages: {'[+]': ['textmacros']}
      },
      loader: {
        load: ['[tex]/textmacros']
      },
      svg: { 
        mtextInheritFont: true, 
        displayAlign: 'left', 
        displayIndent: '2em',
        fontCache: 'global'
      }
    }"
```
