### ISSUE TITLE
Prime and double prime - Mathjax 3/ AsciiMath

### ISSUE THREAD

**Issue by sqlpac** [mathjax/MathJax#2676]
Bonjour, 

Thank you for version 3.1.3 release with AsciiMath upgraded to version 2, we use class { } in AsciiMath. But we have found an issue on prime and double prime with MathJax 3/AsciiMath

### Prime and double prime wrong formatting MathJax 3 / AsciiMath

Input config : input/tex, input/asciimath. Output config : output/chtml. Reproduced in MathJax versions 3.0.5, 3.1.2 and 3.1.4, Chrome and Firefox.

![prime](https://user-images.githubusercontent.com/50557334/116156316-99099700-a6eb-11eb-8642-400c75d36964.png)

Prime and double prime are not in the right container (superscript, mjx-var).

As a workaround, temporarily, we have set the following CSS rule : it's not perfect compared to Tex but acceptable.

```css
        :not([class="mjx-var"][size="s"]) > [class="mjx-c2032"] {
                vertical-align: 0.513em;
                margin-left: 0.025em;
                font-size: 70.7%;
        }
```
