### ISSUE TITLE
v3.2 Lazy mode. Thank you. We expected it, you did it !

### ISSUE THREAD

**Issue by sqlpac** [mathjax/MathJax#2719]
Bonjour,

This is not a feature request, this is not a bug report. Maybe a tiny update in the official doc pointing out that the IntersectionObserver is used, so CSS properties have to be refined for macros defined in hidden tags using the CSS property display: none.

Thank you. We expected it, you did it ! Great work, well done. We have immediately migrated to version 3.2 in lazy mode : no more blocking time in pages, great performances. Excellent.
To manage macros in hidden tags, we migrated the display:none property to position:fixed, height:0, width:0 to ensure they are in the viewport and computed immediately even if the user is scrolled to any location in the page by an anchor.

```css  
  ins[class*="math"][class*="macros"]  { display: none; }
```
by  
```css
  ins[class*="math"][class*="macros"] {
    position: fixed; top: 10px; height: 0px; width: 0px;
    color: transparent; background-color: transparent;
}
```

[A page blocking before v 3.2 lazy mode]https://www.sqlpac.com/en/documents/mathjax-tex-practical-handbook-quick-reference.html()
[Another page blocking before v 3.2 lazy mode](https://www.sqlpac.com/espace-sciences/maths/derivation-applications-formes-indeterminees-regle-de-l-hopital.html)
